#!/bin/sh

VAR1=$1

# if - vypise prvni argument, pokud je zadany
if [ "$#" -eq "1" ]; then
	echo $VAR1
# elif - zkontroluje, zda je druhy argument soubor nebo slozka
elif [ "$#" -eq "2" ]; then
	echo "Zadali jste: "$VAR1
	if [ -f "$2" ]; then
		echo $2" je soubor"
	elif [ -d "$2" ]; then
		echo $2" je slozka"
	else
		echo $2" neni soubor ani slozka"
	fi
fi
