#!/bin/sh

VAR1=$1
VAR2=$2

# IF, ELIF, ELSE
echo "IF statement"
# if - vypise prvni argument, pokud je zadany
if [ "$#" -eq "1" ]; then
	echo $VAR1
# elif - zkontroluje, zda je druhy argument soubor nebo slozka
elif [ "$#" -eq "2" ]; then
	echo "Zadali jste: "$VAR1
	if [ -f "$2" ]; then
		echo $2" je soubor"
	elif [ -d "$2" ]; then
		echo $2" je slozka"
	else
		echo $2" neni soubor ani slozka"
	fi
fi

# CASE
echo "\nCASE statement"
# jednotlive cases se ukoncuji dvema stredniky
case $# in
1) echo $VAR1 ;;
2) if [ -f "$2" ]; then
        echo $2" je soubor"
   elif [ -d "$2" ]; then
	    echo $2" je slozka"
   else
	    echo $2" neni soubor ani slozka"
   fi ;;
*) echo "Nebyly zadany zadne argumenty." ;;
esac
